// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UnitInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnitInfo) Reset()         { *m = UnitInfo{} }
func (m *UnitInfo) String() string { return proto.CompactTextString(m) }
func (*UnitInfo) ProtoMessage()    {}
func (*UnitInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *UnitInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnitInfo.Unmarshal(m, b)
}
func (m *UnitInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnitInfo.Marshal(b, m, deterministic)
}
func (m *UnitInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnitInfo.Merge(m, src)
}
func (m *UnitInfo) XXX_Size() int {
	return xxx_messageInfo_UnitInfo.Size(m)
}
func (m *UnitInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UnitInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UnitInfo proto.InternalMessageInfo

func (m *UnitInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Info struct {
	Name                 string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Units                []*UnitInfo `protobuf:"bytes,2,rep,name=Units,proto3" json:"Units,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Info) GetUnits() []*UnitInfo {
	if m != nil {
		return m.Units
	}
	return nil
}

type Node struct {
	Host                 string   `protobuf:"bytes,1,opt,name=Host,proto3" json:"Host,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=Ip,proto3" json:"Ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Node) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type NodeInfo struct {
	Outcome              *Outcome `protobuf:"bytes,1,opt,name=Outcome,proto3" json:"Outcome,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=Ip,proto3" json:"Ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetOutcome() *Outcome {
	if m != nil {
		return m.Outcome
	}
	return nil
}

func (m *NodeInfo) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NodeInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type Solution struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Solution) Reset()         { *m = Solution{} }
func (m *Solution) String() string { return proto.CompactTextString(m) }
func (*Solution) ProtoMessage()    {}
func (*Solution) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *Solution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Solution.Unmarshal(m, b)
}
func (m *Solution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Solution.Marshal(b, m, deterministic)
}
func (m *Solution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Solution.Merge(m, src)
}
func (m *Solution) XXX_Size() int {
	return xxx_messageInfo_Solution.Size(m)
}
func (m *Solution) XXX_DiscardUnknown() {
	xxx_messageInfo_Solution.DiscardUnknown(m)
}

var xxx_messageInfo_Solution proto.InternalMessageInfo

func (m *Solution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Pool struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pool) Reset()         { *m = Pool{} }
func (m *Pool) String() string { return proto.CompactTextString(m) }
func (*Pool) ProtoMessage()    {}
func (*Pool) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *Pool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pool.Unmarshal(m, b)
}
func (m *Pool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pool.Marshal(b, m, deterministic)
}
func (m *Pool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pool.Merge(m, src)
}
func (m *Pool) XXX_Size() int {
	return xxx_messageInfo_Pool.Size(m)
}
func (m *Pool) XXX_DiscardUnknown() {
	xxx_messageInfo_Pool.DiscardUnknown(m)
}

var xxx_messageInfo_Pool proto.InternalMessageInfo

func (m *Pool) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

type Outcome struct {
	Error                bool     `protobuf:"varint,1,opt,name=error,proto3" json:"error,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Outcome) Reset()         { *m = Outcome{} }
func (m *Outcome) String() string { return proto.CompactTextString(m) }
func (*Outcome) ProtoMessage()    {}
func (*Outcome) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *Outcome) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Outcome.Unmarshal(m, b)
}
func (m *Outcome) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Outcome.Marshal(b, m, deterministic)
}
func (m *Outcome) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Outcome.Merge(m, src)
}
func (m *Outcome) XXX_Size() int {
	return xxx_messageInfo_Outcome.Size(m)
}
func (m *Outcome) XXX_DiscardUnknown() {
	xxx_messageInfo_Outcome.DiscardUnknown(m)
}

var xxx_messageInfo_Outcome proto.InternalMessageInfo

func (m *Outcome) GetError() bool {
	if m != nil {
		return m.Error
	}
	return false
}

func (m *Outcome) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UnitInfo)(nil), "api.UnitInfo")
	proto.RegisterType((*Info)(nil), "api.Info")
	proto.RegisterType((*Node)(nil), "api.Node")
	proto.RegisterType((*NodeInfo)(nil), "api.NodeInfo")
	proto.RegisterType((*Solution)(nil), "api.Solution")
	proto.RegisterType((*Pool)(nil), "api.Pool")
	proto.RegisterType((*Void)(nil), "api.Void")
	proto.RegisterType((*Outcome)(nil), "api.Outcome")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 445 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x94, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x80, 0x69, 0xe2, 0xdf, 0x29, 0xe5, 0xb0, 0xe2, 0x60, 0xe5, 0x50, 0x15, 0xd3, 0xa6, 0x81,
	0x43, 0x0f, 0xe6, 0xc4, 0x09, 0x85, 0x16, 0x89, 0x48, 0xa8, 0x54, 0xb6, 0xe8, 0x11, 0x69, 0x1b,
	0x2f, 0xc5, 0xaa, 0xe3, 0x59, 0xed, 0xae, 0x11, 0x3c, 0x0b, 0x0f, 0xc2, 0xeb, 0xa1, 0x59, 0xff,
	0x48, 0x28, 0x21, 0xf6, 0x85, 0x13, 0xb7, 0xdd, 0x99, 0x2f, 0xdf, 0xce, 0xcc, 0x6e, 0x0c, 0x21,
	0x97, 0xc5, 0x85, 0x54, 0x68, 0x90, 0x4d, 0xb9, 0x2c, 0xe2, 0x63, 0x08, 0x3e, 0x55, 0x85, 0x59,
	0x55, 0x5f, 0x90, 0x31, 0x70, 0xae, 0xf9, 0x46, 0x44, 0x07, 0x27, 0x07, 0x8b, 0x30, 0xb5, 0xeb,
	0xf8, 0x0d, 0x38, 0x7f, 0xcb, 0xb1, 0xe7, 0xe0, 0xd2, 0x6f, 0x75, 0x34, 0x39, 0x99, 0x2e, 0x0e,
	0x93, 0xa3, 0x0b, 0x72, 0x77, 0xb6, 0xb4, 0xc9, 0xc5, 0x2f, 0xc1, 0xb9, 0xc6, 0x5c, 0x90, 0xe0,
	0x3d, 0x6a, 0xd3, 0x09, 0x68, 0xcd, 0x9e, 0xc0, 0x64, 0x25, 0xa3, 0x89, 0x8d, 0x4c, 0x56, 0x32,
	0xfe, 0x0c, 0x01, 0xb1, 0xf6, 0xc0, 0x39, 0xf8, 0x1f, 0x6b, 0xb3, 0xc6, 0xf6, 0xcc, 0xc3, 0xe4,
	0xb1, 0xd5, 0xb7, 0xb1, 0xb4, 0x4b, 0xb2, 0x19, 0x04, 0xe4, 0xaa, 0xa8, 0xb8, 0xc6, 0xd4, 0xef,
	0x5b, 0xff, 0xb4, 0xf7, 0x1f, 0x43, 0x90, 0x61, 0x59, 0x9b, 0x02, 0xab, 0x9d, 0xcd, 0xce, 0xc0,
	0xb9, 0x41, 0x2c, 0x77, 0xe6, 0x3c, 0x70, 0x6e, 0xb1, 0xc8, 0xe3, 0xd7, 0x7d, 0x5d, 0xec, 0x29,
	0xb8, 0x42, 0x29, 0x54, 0x96, 0x0b, 0xd2, 0x66, 0xc3, 0x22, 0xf0, 0x37, 0x42, 0x6b, 0x7e, 0xdf,
	0xd5, 0xd3, 0x6d, 0x93, 0x5f, 0x2e, 0x38, 0x4b, 0x9d, 0xe7, 0xec, 0x14, 0xfc, 0x5b, 0xa1, 0x34,
	0x95, 0x11, 0xda, 0xae, 0xc8, 0x3c, 0xfb, 0xa3, 0xc1, 0xf8, 0x11, 0x7b, 0x46, 0xa3, 0x2f, 0x4c,
	0x8b, 0x50, 0x61, 0x5b, 0xc8, 0x29, 0xf8, 0x34, 0xb0, 0x65, 0x9e, 0xb7, 0x14, 0xed, 0xb6, 0xa8,
	0x73, 0x00, 0x8a, 0xa7, 0x62, 0x83, 0xdf, 0xc4, 0x3e, 0x70, 0x0e, 0x21, 0xc5, 0x6f, 0x6a, 0x75,
	0x2f, 0xf6, 0x0b, 0xbd, 0x4b, 0x25, 0xb8, 0x11, 0xac, 0xb9, 0xf3, 0x6e, 0xa8, 0x5b, 0xe0, 0x02,
	0xfc, 0x2b, 0xa1, 0x8d, 0xc2, 0x1f, 0x43, 0xe4, 0x39, 0x78, 0x6f, 0xf9, 0xfa, 0xa1, 0x96, 0x23,
	0x94, 0xa9, 0xd0, 0x06, 0x95, 0x18, 0xa1, 0xbc, 0x12, 0xb2, 0x1c, 0x3e, 0xdb, 0x2a, 0x0d, 0x35,
	0x34, 0x44, 0xce, 0xc1, 0xcd, 0x0c, 0x57, 0x83, 0xdc, 0x19, 0x38, 0x99, 0x41, 0x39, 0xa2, 0xc2,
	0x77, 0xdf, 0x25, 0xea, 0x31, 0x73, 0xbc, 0xc4, 0xca, 0xf0, 0xa2, 0x1a, 0x22, 0x5f, 0x40, 0x90,
	0x55, 0x5c, 0xea, 0xaf, 0x68, 0x46, 0xa0, 0x29, 0x96, 0xe5, 0x1d, 0x5f, 0x3f, 0x0c, 0xa0, 0xc9,
	0xcf, 0x29, 0x78, 0x4b, 0x9d, 0x7f, 0x10, 0x66, 0xe4, 0xdb, 0x3d, 0xdb, 0xf9, 0x30, 0x8f, 0xfa,
	0x25, 0xfd, 0xc5, 0xff, 0xd1, 0xcb, 0xfc, 0xef, 0xee, 0xfc, 0xce, 0xb3, 0xdf, 0xf3, 0x57, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xb3, 0x83, 0xeb, 0xdc, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AsddClient is the client API for Asdd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AsddClient interface {
	Version(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Outcome, error)
	Init(ctx context.Context, in *Pool, opts ...grpc.CallOption) (*Outcome, error)
	NodeAdd(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error)
	NodeRemove(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error)
	NodePurge(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error)
	Create(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Destroy(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Backup(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Restore(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Deploy(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Retreat(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Start(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Stop(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Expose(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Contain(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Snapshot(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Rollback(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
}

type asddClient struct {
	cc *grpc.ClientConn
}

func NewAsddClient(cc *grpc.ClientConn) AsddClient {
	return &asddClient{cc}
}

func (c *asddClient) Version(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Init(ctx context.Context, in *Pool, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) NodeAdd(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/NodeAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) NodeRemove(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/NodeRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) NodePurge(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/NodePurge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Create(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Destroy(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Backup(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Backup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Restore(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Deploy(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Retreat(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Retreat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Start(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Stop(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Expose(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Expose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Contain(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Contain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Snapshot(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Snapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asddClient) Rollback(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.Asdd/Rollback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsddServer is the server API for Asdd service.
type AsddServer interface {
	Version(context.Context, *Void) (*Outcome, error)
	Init(context.Context, *Pool) (*Outcome, error)
	NodeAdd(context.Context, *Node) (*Outcome, error)
	NodeRemove(context.Context, *Node) (*Outcome, error)
	NodePurge(context.Context, *Node) (*Outcome, error)
	Create(context.Context, *Solution) (*Outcome, error)
	Destroy(context.Context, *Solution) (*Outcome, error)
	Backup(context.Context, *Solution) (*Outcome, error)
	Restore(context.Context, *Solution) (*Outcome, error)
	Deploy(context.Context, *Solution) (*Outcome, error)
	Retreat(context.Context, *Solution) (*Outcome, error)
	Start(context.Context, *Solution) (*Outcome, error)
	Stop(context.Context, *Solution) (*Outcome, error)
	Expose(context.Context, *Solution) (*Outcome, error)
	Contain(context.Context, *Solution) (*Outcome, error)
	Snapshot(context.Context, *Solution) (*Outcome, error)
	Rollback(context.Context, *Solution) (*Outcome, error)
}

// UnimplementedAsddServer can be embedded to have forward compatible implementations.
type UnimplementedAsddServer struct {
}

func (*UnimplementedAsddServer) Version(ctx context.Context, req *Void) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedAsddServer) Init(ctx context.Context, req *Pool) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (*UnimplementedAsddServer) NodeAdd(ctx context.Context, req *Node) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeAdd not implemented")
}
func (*UnimplementedAsddServer) NodeRemove(ctx context.Context, req *Node) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeRemove not implemented")
}
func (*UnimplementedAsddServer) NodePurge(ctx context.Context, req *Node) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodePurge not implemented")
}
func (*UnimplementedAsddServer) Create(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedAsddServer) Destroy(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}
func (*UnimplementedAsddServer) Backup(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Backup not implemented")
}
func (*UnimplementedAsddServer) Restore(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (*UnimplementedAsddServer) Deploy(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (*UnimplementedAsddServer) Retreat(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retreat not implemented")
}
func (*UnimplementedAsddServer) Start(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedAsddServer) Stop(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedAsddServer) Expose(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expose not implemented")
}
func (*UnimplementedAsddServer) Contain(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Contain not implemented")
}
func (*UnimplementedAsddServer) Snapshot(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (*UnimplementedAsddServer) Rollback(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rollback not implemented")
}

func RegisterAsddServer(s *grpc.Server, srv AsddServer) {
	s.RegisterService(&_Asdd_serviceDesc, srv)
}

func _Asdd_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Version(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Init(ctx, req.(*Pool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_NodeAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).NodeAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/NodeAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).NodeAdd(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_NodeRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).NodeRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/NodeRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).NodeRemove(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_NodePurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).NodePurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/NodePurge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).NodePurge(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Create(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Destroy(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Backup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Backup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Backup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Backup(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Restore(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Deploy(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Retreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Retreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Retreat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Retreat(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Start(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Stop(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Expose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Expose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Expose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Expose(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Contain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Contain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Contain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Contain(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Snapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Snapshot(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Asdd_Rollback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsddServer).Rollback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Asdd/Rollback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsddServer).Rollback(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

var _Asdd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Asdd",
	HandlerType: (*AsddServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Asdd_Version_Handler,
		},
		{
			MethodName: "Init",
			Handler:    _Asdd_Init_Handler,
		},
		{
			MethodName: "NodeAdd",
			Handler:    _Asdd_NodeAdd_Handler,
		},
		{
			MethodName: "NodeRemove",
			Handler:    _Asdd_NodeRemove_Handler,
		},
		{
			MethodName: "NodePurge",
			Handler:    _Asdd_NodePurge_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Asdd_Create_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _Asdd_Destroy_Handler,
		},
		{
			MethodName: "Backup",
			Handler:    _Asdd_Backup_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Asdd_Restore_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _Asdd_Deploy_Handler,
		},
		{
			MethodName: "Retreat",
			Handler:    _Asdd_Retreat_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _Asdd_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Asdd_Stop_Handler,
		},
		{
			MethodName: "Expose",
			Handler:    _Asdd_Expose_Handler,
		},
		{
			MethodName: "Contain",
			Handler:    _Asdd_Contain_Handler,
		},
		{
			MethodName: "Snapshot",
			Handler:    _Asdd_Snapshot_Handler,
		},
		{
			MethodName: "Rollback",
			Handler:    _Asdd_Rollback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// AsdLetClient is the client API for AsdLet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AsdLetClient interface {
	Version(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Outcome, error)
	NodeAdd(ctx context.Context, in *Node, opts ...grpc.CallOption) (*NodeInfo, error)
	NodeRemove(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error)
	NodePurge(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error)
	Deploy(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Retreat(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Start(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Stop(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Expose(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
	Contain(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error)
}

type asdLetClient struct {
	cc *grpc.ClientConn
}

func NewAsdLetClient(cc *grpc.ClientConn) AsdLetClient {
	return &asdLetClient{cc}
}

func (c *asdLetClient) Version(ctx context.Context, in *Void, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) NodeAdd(ctx context.Context, in *Node, opts ...grpc.CallOption) (*NodeInfo, error) {
	out := new(NodeInfo)
	err := c.cc.Invoke(ctx, "/api.AsdLet/NodeAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) NodeRemove(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/NodeRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) NodePurge(ctx context.Context, in *Node, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/NodePurge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) Deploy(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Deploy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) Retreat(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Retreat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) Start(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Start", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) Stop(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) Expose(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Expose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *asdLetClient) Contain(ctx context.Context, in *Solution, opts ...grpc.CallOption) (*Outcome, error) {
	out := new(Outcome)
	err := c.cc.Invoke(ctx, "/api.AsdLet/Contain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AsdLetServer is the server API for AsdLet service.
type AsdLetServer interface {
	Version(context.Context, *Void) (*Outcome, error)
	NodeAdd(context.Context, *Node) (*NodeInfo, error)
	NodeRemove(context.Context, *Node) (*Outcome, error)
	NodePurge(context.Context, *Node) (*Outcome, error)
	Deploy(context.Context, *Solution) (*Outcome, error)
	Retreat(context.Context, *Solution) (*Outcome, error)
	Start(context.Context, *Solution) (*Outcome, error)
	Stop(context.Context, *Solution) (*Outcome, error)
	Expose(context.Context, *Solution) (*Outcome, error)
	Contain(context.Context, *Solution) (*Outcome, error)
}

// UnimplementedAsdLetServer can be embedded to have forward compatible implementations.
type UnimplementedAsdLetServer struct {
}

func (*UnimplementedAsdLetServer) Version(ctx context.Context, req *Void) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedAsdLetServer) NodeAdd(ctx context.Context, req *Node) (*NodeInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeAdd not implemented")
}
func (*UnimplementedAsdLetServer) NodeRemove(ctx context.Context, req *Node) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodeRemove not implemented")
}
func (*UnimplementedAsdLetServer) NodePurge(ctx context.Context, req *Node) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NodePurge not implemented")
}
func (*UnimplementedAsdLetServer) Deploy(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deploy not implemented")
}
func (*UnimplementedAsdLetServer) Retreat(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retreat not implemented")
}
func (*UnimplementedAsdLetServer) Start(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (*UnimplementedAsdLetServer) Stop(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (*UnimplementedAsdLetServer) Expose(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expose not implemented")
}
func (*UnimplementedAsdLetServer) Contain(ctx context.Context, req *Solution) (*Outcome, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Contain not implemented")
}

func RegisterAsdLetServer(s *grpc.Server, srv AsdLetServer) {
	s.RegisterService(&_AsdLet_serviceDesc, srv)
}

func _AsdLet_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Version(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_NodeAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).NodeAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/NodeAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).NodeAdd(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_NodeRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).NodeRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/NodeRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).NodeRemove(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_NodePurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).NodePurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/NodePurge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).NodePurge(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_Deploy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Deploy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Deploy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Deploy(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_Retreat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Retreat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Retreat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Retreat(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Start",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Start(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Stop(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_Expose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Expose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Expose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Expose(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

func _AsdLet_Contain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Solution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AsdLetServer).Contain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AsdLet/Contain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AsdLetServer).Contain(ctx, req.(*Solution))
	}
	return interceptor(ctx, in, info, handler)
}

var _AsdLet_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AsdLet",
	HandlerType: (*AsdLetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _AsdLet_Version_Handler,
		},
		{
			MethodName: "NodeAdd",
			Handler:    _AsdLet_NodeAdd_Handler,
		},
		{
			MethodName: "NodeRemove",
			Handler:    _AsdLet_NodeRemove_Handler,
		},
		{
			MethodName: "NodePurge",
			Handler:    _AsdLet_NodePurge_Handler,
		},
		{
			MethodName: "Deploy",
			Handler:    _AsdLet_Deploy_Handler,
		},
		{
			MethodName: "Retreat",
			Handler:    _AsdLet_Retreat_Handler,
		},
		{
			MethodName: "Start",
			Handler:    _AsdLet_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _AsdLet_Stop_Handler,
		},
		{
			MethodName: "Expose",
			Handler:    _AsdLet_Expose_Handler,
		},
		{
			MethodName: "Contain",
			Handler:    _AsdLet_Contain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
